name: Validar Markdown

on:
  push:
    branches: [ main, feature/docs ]
  pull_request:
    branches: [ main ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: .markdownlint.json
          # Esta acción fallará automáticamente si encuentra errores